import {
  AlarmClock, Apple, BookOpenCheck, Brain, Building2, Cake, CalendarDays, CloudRain, Cog, Droplets, Eye, FlaskConical, Gamepad2, Gauge, Globe2,
  Hammer, Heart, HelpCircle, Home, Landmark, Mouse, PartyPopper, PenLine, Scale, Search, ShieldCheck, Sprout, Swords, Train, Trophy, Users, UtensilsCrossed, Waves, Wind,
} from "lucide-react";
import type { LabSpec } from "./lab";
import { WORLDS_A } from "./worldsA";
import { WORLDS_B } from "./worldsB";

/* ══════════════════════════════════════════════════════════════════════
   Per-question configuration for IEO Class 6 Set B, Paper 3.

   Word blocks are cut only from the printed options, so every phrase the
   student can build is made of the paper's own words. Hints explain how to
   think about the question; none names an option.
   ══════════════════════════════════════════════════════════════════════ */

const W = (n: number) => (n <= 25 ? WORLDS_A[n] : WORLDS_B[n]);

const worryAsk = "Collect the sentences that answer the question, then set your conclusion on the pedestal.";
const sugarAsk = "Collect the passage lines that support your answer before you close the case.";

export const SPECS: Record<number, LabSpec> = {
  1: {
    engine: "WordAssemblyEngine",
    title: "Decision Referee",
    mission: "The referee studies the replay before she rules. Build the words that describe how she seemed.",
    icon: Trophy,
    World: W(1),
    bubbleAt: [0.2, 2.1, -0.3],
    hints: ["The sentence says she did make a decision eventually — so before that, how did she seem?", "After “seemed to” you need a verb in its base form, then a word that describes her."],
    mech: { kind: "assemble", blocks: ["have", "be", "surety", "unsure", "not", "create", "it"] },
  },
  2: {
    engine: "GrammarSimulationEngine",
    title: "Weather Observatory",
    mission: "Watch the rain in the observatory — tap the cloud to seed a heavier shower — then spin the verb drum.",
    icon: CloudRain,
    World: W(2),
    camera: { position: [0, 2.2, 5.2], target: [0, 1.3, 0] },
    bubbleAt: [-0.3, 3.9, -0.6],
    hints: ["“always” tells you this is something that is true every time, not one past event.", "The subject “rain” is singular."],
    mech: { kind: "drum", machine: "Rain verb drum" },
  },
  3: {
    engine: "WordAssemblyEngine",
    title: "Trattoria Timeline",
    mission: "The diner has eaten pasta all their life in Italy — and this plate beats them all. Build the words for the blank.",
    icon: UtensilsCrossed,
    World: W(3),
    bubbleAt: [0.1, 2.0, 0.8],
    hints: ["“in my life” means from birth up to now.", "The sentence needs a subject and a verb form that joins the past to the present."],
    mech: { kind: "assemble", blocks: ["I", "I've", "will", "never", "did"] },
  },
  4: {
    engine: "WordAssemblyEngine",
    title: "Performance Analyser",
    mission: "Tonight's bars sit far below the band's usual nights. Build the missing word from its root and an ending.",
    icon: Gauge,
    World: W(4),
    bubbleAt: [0, 2.1, -0.6],
    hints: ["The gap follows “not really” and comes before “of how we usually perform”.", "Which ending turns the root into a word that describes something (“… of something”)?"],
    mech: { kind: "assemble", blocks: ["indicat", "+e", "+ive", "+ively", "+ions"], tray: "Word-part blocks — a root and its endings" },
  },
  5: {
    engine: "VocabularyEngine",
    title: "Ocean Scale Explorer",
    mission: "The sailor has lowered the binoculars — the whale can be seen without them. Pin the plaque that describes the whale.",
    icon: Waves,
    World: W(5),
    camera: { position: [0.5, 2.4, 5.4], target: [0, 0.6, -1] },
    hints: ["Why can something be clearly seen far away without help?", "The word describes the whale's size."],
    mech: { kind: "badge", target: "whale" },
  },
  6: {
    engine: "GrammarSimulationEngine",
    title: "Bonus Board",
    mission: "No bonus for this team. Study the dashboard, then spin the prefix drum that fits in front of “performing”.",
    icon: Gauge,
    World: W(6),
    bubbleAt: [2.2, 2.1, 0.6],
    hints: ["Compare every bar with the yellow target line.", "People who miss a bonus usually did not reach the target."],
    mech: { kind: "drum", machine: "Prefix drum" },
  },
  7: {
    engine: "ConnectorEngine",
    title: "Graffiti Investigation Board",
    mission: "Link the trouble to its cause on the detective's board: thread the word that completes “___ account of”.",
    icon: Search,
    World: W(7),
    bubbleAt: [0.5, 2.1, 0.4],
    hints: ["“___ account of” is a fixed phrase meaning “because of”.", "Only one of the connectors forms that phrase."],
    mech: { kind: "link", left: "I think this trouble is …", right: "… account of the problems with graffiti at school." },
  },
  8: {
    engine: "WordAssemblyEngine",
    title: "Missing Water Mystery",
    mission: "The cold water is gone and the bottle is empty. Build what the little sister did.",
    icon: Droplets,
    World: W(8),
    bubbleAt: [-0.3, 2.0, 0.8],
    hints: ["The water is already gone — the action is finished and in the past.", "“who ___ all my cold water” needs one complete verb."],
    mech: { kind: "assemble", blocks: ["will", "have", "drink", "finish", "+ed", "+ing"] },
  },
  9: {
    engine: "PunctuationEngine",
    title: "Punctuation Repair Shop",
    mission: "The teacher's words are a question inside quotation marks. Key the marks that belong in the gap.",
    icon: PenLine,
    World: W(9),
    template: "“Do you know the answer ___ asked the teacher.",
    hints: ["The teacher's words ask something.", "Speech marks close after the teacher's own punctuation."],
    mech: { kind: "punctuate", marks: ["?", "!", ".", "\"", ","], slots: 2, before: "“Do you know the answer", after: " asked the teacher." },
  },
  10: {
    engine: "WordAssemblyEngine",
    title: "Party Planner",
    mission: "You and Katy are going to the party. Build the words that bring me along too.",
    icon: PartyPopper,
    World: W(10),
    bubbleAt: [0, 2.1, 0.7],
    hints: ["You want a phrase that means “too” and can end a sentence.", "Try saying the whole sentence aloud with your phrase."],
    mech: { kind: "assemble", blocks: ["as", "well", "if", "into", "through"] },
  },
  11: {
    engine: "GrammarSimulationEngine",
    title: "Train Disruption Simulator",
    mission: "The 07:45 is cancelled and the car is waiting. Spin the drum to complete the plan.",
    icon: Train,
    World: W(11),
    bubbleAt: [0, 2.3, -0.5],
    hints: ["The train being cancelled forces a different way to work.", "Read the whole sentence with each word before you decide."],
    mech: { kind: "drum", machine: "Commute planner" },
  },
  12: {
    engine: "ConnectorEngine",
    title: "The Old Mill",
    mission: "The house was once a working mill. Thread the connector that joins that fact to its name.",
    icon: Landmark,
    World: W(12),
    bubbleAt: [-0.4, 2.1, 1.2],
    hints: ["The name comes from the building's past — you need a word meaning “for this reason”.", "The connector must work right before “the name”."],
    mech: { kind: "link", left: "‘The Old Mill’ used to be a working mill, …", right: "… the name." },
  },
  13: {
    engine: "GrammarSimulationEngine",
    title: "Wedding Tissue Counter",
    mission: "Tears at the wedding — and no tissues. Spin the drum for the word before “tissue”.",
    icon: Heart,
    World: W(13),
    bubbleAt: [1, 2.0, 0.35],
    hints: ["Here “tissue” is used like an uncountable amount.", "Which word talks about an amount of something?"],
    mech: { kind: "drum", machine: "Quantity drum" },
  },
  14: {
    engine: "WordAssemblyEngine",
    title: "Picnic Crumbs",
    mission: "A lovely picnic — and crumbs everywhere. Build the verb form that follows “couldn't help”.",
    icon: Wind,
    World: W(14),
    bubbleAt: [-0.9, 1.8, 0.3],
    hints: ["“can't help” / “couldn't help” is followed by a particular verb form.", "Think of “I can't help laughing”."],
    mech: { kind: "assemble", blocks: ["to", "be", "were", "scatter", "+ed", "+ing"] },
  },
  15: {
    engine: "WordAssemblyEngine",
    title: "Toy Train Room",
    mission: "It's yesterday morning, before nursery. Build what he did with his toy train.",
    icon: Train,
    World: W(15),
    bubbleAt: [0.1, 1.6, 0.2],
    hints: ["“yesterday” sets the time.", "He is the one doing the action."],
    mech: { kind: "assemble", blocks: ["was", "play", "+ed", "+s", "to"] },
  },
  16: {
    engine: "ConnectorEngine",
    title: "Puppy Encounter",
    mission: "Meeting the puppy sends you tumbling. Thread the word that joins “head” and “heels”.",
    icon: Heart,
    World: W(16),
    bubbleAt: [-0.5, 2.3, 0.3],
    hints: ["The idiom pictures someone tumbling right over.", "Your head goes where your heels were."],
    mech: { kind: "link", left: "When I met my new puppy, I fell head …", right: "… heels because he is just so cute." },
  },
  17: {
    engine: "TimelineEngine",
    title: "24-Hour Revision Clock",
    mission: "Revision day and night. Turn the dial's hand to the word that completes “working ___ the clock”.",
    icon: AlarmClock,
    World: W(17),
    bubbleAt: [0.9, 1.9, 0.7],
    hints: ["The idiom means working all day and all night.", "Picture the hands going all the way round the face."],
    mech: {
      kind: "scale",
      shape: "ring",
      stops: [
        { option: "A", at: 0.125 },
        { option: "B", at: 0.375 },
        { option: "C", at: 0.625 },
        { option: "D", at: 0.875 },
      ],
      ticks: [{ at: 0, label: "12" }, { at: 0.25, label: "3" }, { at: 0.5, label: "6" }, { at: 0.75, label: "9" }],
    },
  },
  18: {
    engine: "VocabularyEngine",
    title: "Savanna Conservation Station",
    mission: "A ranger records the herd. Pin the plaque that names what the speaker hopes never to see.",
    icon: ShieldCheck,
    World: W(18),
    camera: { position: [0, 2.4, 5], target: [0, 0.7, -0.5] },
    hints: ["After “the” you need a noun.", "What would the end of all elephants be called?"],
    mech: { kind: "badge", target: "herd's record book", verb: "Write it in" },
  },
  19: {
    engine: "WordAssemblyEngine",
    title: "City Arrival",
    mission: "A newcomer arrives with a suitcase and knows nobody. Build what they had to make an effort to do.",
    icon: Building2,
    World: W(19),
    bubbleAt: [0.2, 2.1, 0.3],
    hints: ["The verb goes with “myself”.", "It means to settle and make a secure place for yourself."],
    mech: { kind: "assemble", blocks: ["put", "up", "establish", "ask", "allow"] },
  },
  20: {
    engine: "VocabularyEngine",
    title: "Behaviour Judge",
    mission: "The visitors look on in surprise. Pin the plaque that describes the way the children behaved.",
    icon: Scale,
    World: W(20),
    hints: ["The sentence says it was especially bad because visitors were there.", "Look for a word meaning very unpleasant or shameful."],
    mech: { kind: "badge", target: "behaviour report", verb: "Stamp it on" },
  },
  21: {
    engine: "VocabularyEngine",
    title: "Swallow Migration Globe",
    mission: "Follow the swallows' seasonal route across the globe, then pin the verb for their journey.",
    icon: Globe2,
    World: W(21),
    camera: { position: [0, 2.2, 4.6], target: [0, 1.4, 0] },
    hints: ["The subject is “the swallow” — singular.", "Which verb means a seasonal journey from one region to another?"],
    mech: { kind: "badge", target: "flight route", verb: "Label" },
  },
  22: {
    engine: "WordAssemblyEngine",
    title: "Document Security Mission",
    mission: "Carry the papers to the headmaster in the locked case. Build the word that tells how they must be taken.",
    icon: ShieldCheck,
    World: W(22),
    bubbleAt: [-0.6, 2.2, 0.3],
    hints: ["The gap describes how the papers are taken — the word modifies a verb.", "Which ending makes a word that tells “how”?"],
    mech: { kind: "assemble", blocks: ["secur", "+e", "+ely", "+ity", "+ed"], tray: "Word-part blocks — a root and its endings" },
  },
  23: {
    flat: "error",
    engine: "ErrorRepairEngine",
    title: "Tiny Mouse Audio Lab",
    mission: "Listen for the mice, then inspect the sentence under the lens. Flag the faulty part and repair it on the bench.",
    icon: Mouse,
    World: W(23),
    hints: ["Check each noun: is its plural formed correctly?", "Some nouns do not add -s to become plural."],
    mech: { kind: "repair", inspectHint: "Check plurals and apostrophes especially." },
  },
  24: {
    flat: "error",
    engine: "ErrorRepairEngine",
    title: "Twin Identification Lab",
    mission: "Two identical twins on the scanner. Inspect the sentence, flag the faulty part and rewrite it.",
    icon: Users,
    World: W(24),
    hints: ["Whose twin is it? Look for a missing possessive.", "Read each part and ask whether it could stand in a correct sentence."],
    mech: { kind: "repair", inspectHint: "Look closely at who owns what." },
  },
  25: {
    flat: "meaning",
    engine: "VocabularyEngine",
    title: "Apprentice Workshop",
    mission: "A fledgling hops in its nest; a beginner learns from the master. Pin the role that means the same as “fledgling”.",
    icon: Hammer,
    World: W(25),
    hints: ["A fledgling is a young bird just learning to fly.", "Which role describes someone new who is still learning a trade?"],
    mech: { kind: "badge", target: "beginner at the bench", verb: "Pin the role on" },
  },
  26: {
    flat: "meaning",
    engine: "VocabularyEngine",
    title: "Growth Machine",
    mission: "Each turn the machine adds one more coin to the stack. Pin the plaque that means the same as “increment”.",
    icon: Cog,
    World: W(26),
    hints: ["An increment is a small increase added on.", "Which word means amounts building up bit by bit?"],
    mech: { kind: "badge", target: "coin stack" },
  },
  27: {
    flat: "meaning",
    engine: "VocabularyEngine",
    title: "World-View Observatory",
    mission: "The walled village sees only itself; the globe shows the whole world. Pin the opposite of “parochial”.",
    icon: Globe2,
    World: W(27),
    hints: ["Parochial means having a narrow, local outlook.", "Its opposite is open-minded and broad in outlook."],
    mech: { kind: "badge", target: "open globe" },
  },
  28: {
    flat: "meaning",
    engine: "VocabularyEngine",
    title: "Meshing Gears",
    mission: "Gears that mesh fit together smoothly — like friends who get on. Pin the plaque that means the opposite.",
    icon: Cog,
    World: W(28),
    hints: ["As a verb, to mesh is to fit together or to get along well.", "Look for a word that means the opposite of getting along."],
    mech: { kind: "badge", target: "reverse plate" },
  },
  29: {
    engine: "SpellingEngine",
    title: "Word Detective Office",
    mission: "Everything on the desk wears the wrong name tag. Stamp the correctly spelt word for a wrong name.",
    icon: Search,
    World: W(29),
    hints: ["The word starts like “mistake” and “misprint”.", "Its middle part is the Latin for “name”."],
    mech: { kind: "build", blocks: ["mes", "ma", "ner", "mis", "no", "mer", "mos", "mi", "mon", "si"], meaning: "a wrong or unsuitable name (mistake)" },
  },
  30: {
    engine: "SpellingEngine",
    title: "Four Seasons Garden",
    mission: "The annuals come and go; one shrub lasts year after year. Type the correct spelling of the word that means enduring.",
    icon: Sprout,
    World: W(30),
    hints: ["The word is built on the Latin for “year”, like “annual”.", "It has a double n and ends in -ial."],
    mech: { kind: "build", blocks: "keyboard", meaning: "enduring; lasting year after year" },
  },
  31: {
    engine: "ReadingInvestigationEngine",
    title: "Thought Observatory",
    mission: "Worries orbit the desk. Collect the passage's key sentences, then set a title on the title plinth.",
    icon: Brain,
    World: W(31),
    hints: ["What does the writer say about most of our worries?", "A good title covers the whole passage, not one line."],
    mech: { kind: "evidence", ask: worryAsk, pedestal: "Title plinth" },
  },
  32: {
    engine: "ReadingInvestigationEngine",
    title: "Brain Alarm Room",
    mission: "The brain's safety alarm keeps flashing. Collect the chain of sentences that explains why we worry.",
    icon: Brain,
    World: W(32),
    hints: ["Start with the first paragraph: how does every brain work?", "Is worrying something we choose, or something built into us?"],
    mech: { kind: "evidence", ask: worryAsk, chain: true, pedestal: "Cause panel" },
  },
  33: {
    engine: "ReadingInvestigationEngine",
    title: "Ten-Worry Inventory",
    mission: "The writer sets an exercise. Collect the lines that describe it, then place your conclusion.",
    icon: BookOpenCheck,
    World: W(33),
    hints: ["Find the sentence that begins the exercise.", "What does the writer ask you to write down, and how many?"],
    mech: { kind: "evidence", ask: worryAsk },
  },
  34: {
    flat: "reading",
    engine: "TimelineEngine",
    title: "Look-Ahead Calendar",
    mission: "Read the rules for the list, then slide the marker along the time scale to how far ahead to look.",
    icon: CalendarDays,
    World: W(34),
    hints: ["The first rule sets a time frame — find it in the passage.", "The scale is to size: compare days, weeks and months."],
    mech: {
      kind: "scale",
      from: "today",
      to: "3½ years",
      stops: [
        { option: "C", at: 0.0 },
        { option: "A", at: 0.32 },
        { option: "D", at: 0.73 },
        { option: "B", at: 1.0 },
      ],
      ticks: [
        { at: 0.27, label: "1 week" },
        { at: 0.48, label: "1 month" },
        { at: 0.83, label: "1 year" },
      ],
    },
  },
  35: {
    engine: "ReadingInvestigationEngine",
    title: "Focus Lens",
    mission: "Most worries blur; one comes into sharp view. Collect the line with ‘home in on’, then place its meaning.",
    icon: Eye,
    World: W(35),
    hints: ["Find ‘home in on’ in the last paragraph.", "Clearing your mind lets you give your attention to the real concerns."],
    mech: { kind: "evidence", ask: "Collect the sentence where the phrase appears, then set its meaning on the pedestal.", pedestal: "Meaning pedestal" },
  },
  36: {
    engine: "ReadingInvestigationEngine",
    title: "Sugar Detective Lab",
    mission: "Inspect the passage like a food lab: collect the key lines, then project a title on the wall.",
    icon: Apple,
    World: W(36),
    hints: ["What does the expert say worked for her clients?", "A title should fit the whole passage."],
    mech: { kind: "evidence", ask: sugarAsk, pedestal: "Wall projection" },
  },
  37: {
    engine: "ReadingInvestigationEngine",
    title: "Benefit Board",
    mission: "Find what the passage says cutting sugar can do for you, then pin the benefit it names.",
    icon: Apple,
    World: W(37),
    hints: ["The second paragraph lists what reducing sugar can do.", "Only choose a benefit the passage actually states."],
    mech: { kind: "evidence", ask: sugarAsk, pedestal: "Benefit board" },
  },
  38: {
    flat: "reading",
    engine: "TimelineEngine",
    title: "Detox Meal Planner",
    mission: "Find how long the detox runs, then slide the planner's end marker to it.",
    icon: CalendarDays,
    World: W(38),
    hints: ["Search the passage for the word “detox”.", "Three meals make one day on the plan."],
    mech: {
      kind: "scale",
      from: "start",
      to: "for ever",
      stops: [
        { option: "C", at: 0.08 },
        { option: "B", at: 0.3 },
        { option: "D", at: 0.62 },
        { option: "A", at: 1.0 },
      ],
      ticks: [
        { at: 0.08, label: "day 1" },
        { at: 0.3, label: "day 3" },
        { at: 0.62, label: "day 7" },
      ],
    },
  },
  39: {
    engine: "ReadingInvestigationEngine",
    title: "Taste Calibration Lab",
    mission: "Trace the chain in the last paragraph — sweeteners, palate, eating — then place what it leads to.",
    icon: FlaskConical,
    World: W(39),
    hints: ["Read the last paragraph slowly: what do sweeteners do to the palate?", "What do people end up doing later on?"],
    mech: { kind: "evidence", ask: sugarAsk, chain: true, pedestal: "Effect panel" },
  },
  40: {
    engine: "ReadingInvestigationEngine",
    title: "Energy Balance Machine",
    mission: "Collect the sentence with ‘compensate’, then set its meaning on the balance.",
    icon: Scale,
    World: W(40),
    hints: ["People overeat later to balance out something that happened earlier.", "Which meaning fits in place of the word in that sentence?"],
    mech: { kind: "evidence", ask: "Collect the sentence where the word appears, then set its meaning on the pedestal.", pedestal: "Balance pan" },
  },
  41: {
    engine: "VocabularyEngine",
    title: "Construction Challenge",
    mission: "Jimmy's wall is half done and one corner is skipped. Pin the word that finishes Bill's warning.",
    icon: Hammer,
    World: W(41),
    hints: ["Bill means Jimmy does the job badly to save time or money.", "The idiom is “cutting ___” — doing something the quick, careless way."],
    mech: { kind: "badge", target: "warning sign", verb: "Pin it on the" },
  },
  42: {
    engine: "WordAssemblyEngine",
    title: "Breakfast Time Machine",
    mission: "7:30 breakfast was skipped; at 11:00 Bella is starving. Build the words for her regret.",
    icon: UtensilsCrossed,
    World: W(42),
    bubbleAt: [0.7, 2.1, 0.3],
    hints: ["Bella is looking back at something she did not do this morning.", "The words must fit between “I wish I” and “eaten”."],
    mech: { kind: "assemble", blocks: ["should", "have", "had", "will"] },
  },
  43: {
    engine: "GrammarSimulationEngine",
    title: "Cleaning Progress",
    mission: "The bed is made and the shelf is tidy — only the rug is left. Spin the drum for the daughter's reply.",
    icon: Home,
    World: W(43),
    bubbleAt: [0.9, 2.0, 0.6],
    hints: ["The daughter means that only one job is left.", "Which word means “only”?"],
    mech: { kind: "drum", machine: "Reply drum" },
  },
  44: {
    engine: "GrammarSimulationEngine",
    title: "Cake Tin Capacity",
    mission: "One small tin, batter for twelve. Spin the drum for Suzi's reply.",
    icon: Cake,
    World: W(44),
    bubbleAt: [1.2, 2.0, 0],
    hints: ["Suzi goes on to say the tin looks small.", "Does she agree the tin is big enough?"],
    mech: { kind: "drum", machine: "Reply drum" },
  },
  45: {
    engine: "WordAssemblyEngine",
    title: "Missed-Opportunity Timeline",
    mission: "Yesterday was the chance to ask; today it's too late. Build what Sally tells you.",
    icon: HelpCircle,
    World: W(45),
    bubbleAt: [1.1, 2.0, -0.4],
    hints: ["Sally is talking about a past chance that was missed.", "Which form means “it would have been right to”?"],
    mech: { kind: "assemble", blocks: ["will", "should", "+'ve", "maybe"] },
  },
  46: {
    engine: "AchieverPuzzleEngine",
    title: "Storm Crossing",
    mission: "Lead the team through the storm — tap each obstacle in the world or use the task bar — then thread the connector.",
    icon: Swords,
    World: W(46),
    camera: { position: [0, 2.4, 5.4], target: [0, 1, 0] },
    gate: {
      title: "Cross the storm",
      steps: [
        { id: "tree", label: "Climb the fallen tree", action: "tap the log" },
        { id: "wind", label: "Brace against the gust", action: "tap the wind" },
        { id: "shelter", label: "Reach the shelter", action: "tap the hut" },
      ],
    },
    hints: ["The team keeps going even though things are hard.", "You need a word that means “even with” all the difficulties."],
    mech: { kind: "link", left: "There is something we can do …", right: "… all the difficulties." },
  },
  47: {
    engine: "AchieverPuzzleEngine",
    title: "Summer Workload",
    mission: "Load each month's crate of work onto the summer planner, then build the words for the plan.",
    icon: CalendarDays,
    World: W(47),
    gate: {
      title: "Plan the summer",
      steps: [
        { id: "june", label: "Load June's work", action: "tap the first crate" },
        { id: "july", label: "Load July's work", action: "tap the next crate" },
        { id: "august", label: "Load August's work", action: "tap the last crate" },
      ],
    },
    hints: ["“Come the summer” looks ahead to a time when the work will already be piled up.", "Which form talks about something completed by a future time?"],
    mech: { kind: "assemble", blocks: ["I'll", "I'd", "I'm", "have", "had", "being", "having", "to"] },
  },
  48: {
    engine: "AchieverPuzzleEngine",
    title: "Control the Wild Machine",
    mission: "Pull the three levers to bring the shaking machine under control, then pin the synonym of “subdue”.",
    icon: Cog,
    World: W(48),
    gate: {
      title: "Steady the machine",
      steps: [
        { id: "lever1", label: "Pull lever 1", action: "tap the first lever" },
        { id: "lever2", label: "Pull lever 2", action: "tap the next lever" },
        { id: "lever3", label: "Pull lever 3", action: "tap the last lever" },
      ],
    },
    hints: ["To subdue something is to bring it under control or overcome it.", "Which word means to defeat or overcome?"],
    mech: { kind: "badge", target: "control panel" },
  },
  49: {
    engine: "AchieverPuzzleEngine",
    title: "Material Testing Lab",
    mission: "Spray each sample and watch where the water goes. Then pin the word that means the opposite of “porous”.",
    icon: FlaskConical,
    World: W(49),
    camera: { position: [0, 2.2, 4.6], target: [0, 0.7, -0.5] },
    gate: {
      title: "Test the samples",
      steps: [
        { id: "sponge", label: "Spray the sponge", action: "tap the yellow block" },
        { id: "stone", label: "Spray the stone", action: "tap the grey block" },
        { id: "glass", label: "Spray the glass", action: "tap the clear block" },
        { id: "sheet", label: "Spray the waterproof sheet", action: "tap the blue block" },
      ],
    },
    hints: ["A porous material lets water pass through it, like the sponge.", "The opposite describes a material that lets nothing pass through."],
    mech: { kind: "badge", target: "sample that blocks water" },
  },
  50: {
    engine: "AchieverPuzzleEngine",
    title: "Rule Room",
    mission: "Bring both players to the rule board and read the rules together, then build what Felix says.",
    icon: Gamepad2,
    World: W(50),
    gate: {
      title: "Get everyone ready",
      steps: [
        { id: "felix", label: "Bring Felix to the board", action: "tap Felix" },
        { id: "maya", label: "Bring Maya to the board", action: "tap Maya" },
        { id: "rules", label: "Read the rules together", action: "tap the rule board" },
      ],
    },
    hints: ["Felix wants everyone to understand the rules in the same way.", "The idiom pictures everyone reading from the same sheet."],
    mech: { kind: "assemble", blocks: ["best", "easiest", "different", "same", "place", "lines", "course", "page"] },
  },
};
