"use client";

import type { ActivityComponentType } from "../kit/types";
import { Q01BreakfastBeforeWorkActivity, Q02PackingForTheHolidayActivity, Q03HelpingInTheKitchenActivity, Q04TheLanguageGlobeActivity, Q05WaitingForTheBusActivity } from "./p01_05";
import { Q06FiveYearsOnActivity, Q07HeavyBagsActivity, Q08TheMangosteenActivity, Q09WashYourHandsActivity, Q10GeographyClassActivity } from "./p06_10";
import { Q11IceCreamTreatActivity, Q12MissingFromPracticeActivity, Q13ThroughTheStormActivity, Q14TooBusyHereActivity, Q15GoingOnAheadActivity } from "./p11_15";
import { Q16TheWornPlaygroundActivity, Q17HolidayMemoriesActivity, Q18BotanicalNamesActivity, Q19TheLongWaitActivity, Q20TheLuckyChildActivity } from "./p16_20";
import { Q21CopyThePictureActivity, Q22OnePieceTooManyActivity, Q23TheQuietMusicActivity, Q24DetentionActivity, Q25LifeInTheSeaActivity } from "./p21_25";
import { Q26SpotTheMisspellingActivity, Q27TheBeaverTitleActivity, Q28BeaversInSouthAmericaActivity, Q29BeaversBackInEuropeActivity, Q30WhyNumbersFellActivity } from "./p26_30";
import { Q31TheBeaversLookActivity, Q32WhatWentWrongActivity, Q33WhyDamsActivity, Q34MovingToGoaActivity, Q35CloserToFriendsActivity } from "./p31_35";
import { Q36TheNewHouseActivity, Q37WalkingToSchoolActivity, Q38ANewSchoolActivity, Q39MovingInPartyActivity, Q40CookingTogetherActivity } from "./p36_40";
import { Q41TheBruisedKneeActivity, Q42TheNoseyNeighbourActivity, Q43DinnerInvitationActivity, Q44AStitchInTimeActivity, Q45TooTiredToWalkActivity } from "./p41_45";
import { Q46TheDogOnTheBikeActivity, Q47TheSharedKitchenActivity, Q48SwimmingStrokesActivity, Q49SpotTheMisspellingActivity, Q50RepayingAFavourActivity } from "./p46_50";

/**
 * Activity registry for the IEO Class 6 Interactive Master Edition.
 * Maps both internal IDs (ieo_g6_interactive_q01) and question codes (IEO-G6-INT-Q01).
 */
export const IEO_INTERACTIVE_G6_PLAY_ACTIVITY_MAP: Record<string, ActivityComponentType> = {
  ieo_g6_interactive_q01: Q01BreakfastBeforeWorkActivity,
  "IEO-G6-INT-Q01": Q01BreakfastBeforeWorkActivity,
  ieo_g6_interactive_q02: Q02PackingForTheHolidayActivity,
  "IEO-G6-INT-Q02": Q02PackingForTheHolidayActivity,
  ieo_g6_interactive_q03: Q03HelpingInTheKitchenActivity,
  "IEO-G6-INT-Q03": Q03HelpingInTheKitchenActivity,
  ieo_g6_interactive_q04: Q04TheLanguageGlobeActivity,
  "IEO-G6-INT-Q04": Q04TheLanguageGlobeActivity,
  ieo_g6_interactive_q05: Q05WaitingForTheBusActivity,
  "IEO-G6-INT-Q05": Q05WaitingForTheBusActivity,
  ieo_g6_interactive_q06: Q06FiveYearsOnActivity,
  "IEO-G6-INT-Q06": Q06FiveYearsOnActivity,
  ieo_g6_interactive_q07: Q07HeavyBagsActivity,
  "IEO-G6-INT-Q07": Q07HeavyBagsActivity,
  ieo_g6_interactive_q08: Q08TheMangosteenActivity,
  "IEO-G6-INT-Q08": Q08TheMangosteenActivity,
  ieo_g6_interactive_q09: Q09WashYourHandsActivity,
  "IEO-G6-INT-Q09": Q09WashYourHandsActivity,
  ieo_g6_interactive_q10: Q10GeographyClassActivity,
  "IEO-G6-INT-Q10": Q10GeographyClassActivity,
  ieo_g6_interactive_q11: Q11IceCreamTreatActivity,
  "IEO-G6-INT-Q11": Q11IceCreamTreatActivity,
  ieo_g6_interactive_q12: Q12MissingFromPracticeActivity,
  "IEO-G6-INT-Q12": Q12MissingFromPracticeActivity,
  ieo_g6_interactive_q13: Q13ThroughTheStormActivity,
  "IEO-G6-INT-Q13": Q13ThroughTheStormActivity,
  ieo_g6_interactive_q14: Q14TooBusyHereActivity,
  "IEO-G6-INT-Q14": Q14TooBusyHereActivity,
  ieo_g6_interactive_q15: Q15GoingOnAheadActivity,
  "IEO-G6-INT-Q15": Q15GoingOnAheadActivity,
  ieo_g6_interactive_q16: Q16TheWornPlaygroundActivity,
  "IEO-G6-INT-Q16": Q16TheWornPlaygroundActivity,
  ieo_g6_interactive_q17: Q17HolidayMemoriesActivity,
  "IEO-G6-INT-Q17": Q17HolidayMemoriesActivity,
  ieo_g6_interactive_q18: Q18BotanicalNamesActivity,
  "IEO-G6-INT-Q18": Q18BotanicalNamesActivity,
  ieo_g6_interactive_q19: Q19TheLongWaitActivity,
  "IEO-G6-INT-Q19": Q19TheLongWaitActivity,
  ieo_g6_interactive_q20: Q20TheLuckyChildActivity,
  "IEO-G6-INT-Q20": Q20TheLuckyChildActivity,
  ieo_g6_interactive_q21: Q21CopyThePictureActivity,
  "IEO-G6-INT-Q21": Q21CopyThePictureActivity,
  ieo_g6_interactive_q22: Q22OnePieceTooManyActivity,
  "IEO-G6-INT-Q22": Q22OnePieceTooManyActivity,
  ieo_g6_interactive_q23: Q23TheQuietMusicActivity,
  "IEO-G6-INT-Q23": Q23TheQuietMusicActivity,
  ieo_g6_interactive_q24: Q24DetentionActivity,
  "IEO-G6-INT-Q24": Q24DetentionActivity,
  ieo_g6_interactive_q25: Q25LifeInTheSeaActivity,
  "IEO-G6-INT-Q25": Q25LifeInTheSeaActivity,
  ieo_g6_interactive_q26: Q26SpotTheMisspellingActivity,
  "IEO-G6-INT-Q26": Q26SpotTheMisspellingActivity,
  ieo_g6_interactive_q27: Q27TheBeaverTitleActivity,
  "IEO-G6-INT-Q27": Q27TheBeaverTitleActivity,
  ieo_g6_interactive_q28: Q28BeaversInSouthAmericaActivity,
  "IEO-G6-INT-Q28": Q28BeaversInSouthAmericaActivity,
  ieo_g6_interactive_q29: Q29BeaversBackInEuropeActivity,
  "IEO-G6-INT-Q29": Q29BeaversBackInEuropeActivity,
  ieo_g6_interactive_q30: Q30WhyNumbersFellActivity,
  "IEO-G6-INT-Q30": Q30WhyNumbersFellActivity,
  ieo_g6_interactive_q31: Q31TheBeaversLookActivity,
  "IEO-G6-INT-Q31": Q31TheBeaversLookActivity,
  ieo_g6_interactive_q32: Q32WhatWentWrongActivity,
  "IEO-G6-INT-Q32": Q32WhatWentWrongActivity,
  ieo_g6_interactive_q33: Q33WhyDamsActivity,
  "IEO-G6-INT-Q33": Q33WhyDamsActivity,
  ieo_g6_interactive_q34: Q34MovingToGoaActivity,
  "IEO-G6-INT-Q34": Q34MovingToGoaActivity,
  ieo_g6_interactive_q35: Q35CloserToFriendsActivity,
  "IEO-G6-INT-Q35": Q35CloserToFriendsActivity,
  ieo_g6_interactive_q36: Q36TheNewHouseActivity,
  "IEO-G6-INT-Q36": Q36TheNewHouseActivity,
  ieo_g6_interactive_q37: Q37WalkingToSchoolActivity,
  "IEO-G6-INT-Q37": Q37WalkingToSchoolActivity,
  ieo_g6_interactive_q38: Q38ANewSchoolActivity,
  "IEO-G6-INT-Q38": Q38ANewSchoolActivity,
  ieo_g6_interactive_q39: Q39MovingInPartyActivity,
  "IEO-G6-INT-Q39": Q39MovingInPartyActivity,
  ieo_g6_interactive_q40: Q40CookingTogetherActivity,
  "IEO-G6-INT-Q40": Q40CookingTogetherActivity,
  ieo_g6_interactive_q41: Q41TheBruisedKneeActivity,
  "IEO-G6-INT-Q41": Q41TheBruisedKneeActivity,
  ieo_g6_interactive_q42: Q42TheNoseyNeighbourActivity,
  "IEO-G6-INT-Q42": Q42TheNoseyNeighbourActivity,
  ieo_g6_interactive_q43: Q43DinnerInvitationActivity,
  "IEO-G6-INT-Q43": Q43DinnerInvitationActivity,
  ieo_g6_interactive_q44: Q44AStitchInTimeActivity,
  "IEO-G6-INT-Q44": Q44AStitchInTimeActivity,
  ieo_g6_interactive_q45: Q45TooTiredToWalkActivity,
  "IEO-G6-INT-Q45": Q45TooTiredToWalkActivity,
  ieo_g6_interactive_q46: Q46TheDogOnTheBikeActivity,
  "IEO-G6-INT-Q46": Q46TheDogOnTheBikeActivity,
  ieo_g6_interactive_q47: Q47TheSharedKitchenActivity,
  "IEO-G6-INT-Q47": Q47TheSharedKitchenActivity,
  ieo_g6_interactive_q48: Q48SwimmingStrokesActivity,
  "IEO-G6-INT-Q48": Q48SwimmingStrokesActivity,
  ieo_g6_interactive_q49: Q49SpotTheMisspellingActivity,
  "IEO-G6-INT-Q49": Q49SpotTheMisspellingActivity,
  ieo_g6_interactive_q50: Q50RepayingAFavourActivity,
  "IEO-G6-INT-Q50": Q50RepayingAFavourActivity,
};
