/**
 * Activity Archetypes Library — 29 Cognitive Paradigms
 * 
 * A curated collection of 29 foundational cognitive activity paradigms
 * derived from elite Olympiad examination patterns.
 * 
 * IMPORTANT ARCHITECTURAL RULE:
 * These are COGNITIVE METAMODELS and INSPIRATIONAL FOUNDATIONS — NEVER templates
 * to copy-paste. The AI engine must synthesize new, bespoke microworlds for every
 * unique question based on its specific invariant and cognitive tension.
 */

export interface Archetype {
  id: string;
  name: string;
  category: "spatial" | "transformation" | "classification" | "navigation" | "construction" | "physics" | "puzzle" | "data" | "measurement" | "achiever" | "everyday";
  description: string;
  cognitiveSkills: string[];
  interactionPattern: string;
  visualMetaphor: string;
  technology: string[];
  complexity: "low" | "medium" | "high";
  gradeRange: [number, number];
  estimatedTimeSeconds: [number, number];
}

// ─── THE 29 FOUNDATIONAL COGNITIVE PARADIGMS ────────────────

export const THE_29_PARADIGMS: Archetype[] = [
  {
    id: "spatial-3d-inspector",
    name: "3D & Isometric Spatial Inspection",
    category: "spatial",
    description: "Rotational inspection table with multi-view camera tracking (Top/Front/Side) to deduce hidden faces or orientations.",
    cognitiveSkills: ["spatial-reasoning", "3d-rotation", "polyhedral-nets"],
    interactionPattern: "drag-rotate → camera-inspect → deduce-face",
    visualMetaphor: "Laboratory examination turntable or orbital asteroid scanner",
    technology: ["three", "canvas", "svg"],
    complexity: "medium",
    gradeRange: [6, 8],
    estimatedTimeSeconds: [20, 50],
  },
  {
    id: "state-transformation-circuit",
    name: "State-Transition & Mutation Machines",
    category: "transformation",
    description: "Input elements travel through visible transformation stages where underlying rules alter visual/numeric properties.",
    cognitiveSkills: ["sequence-rules", "state-mutation", "matrix-logic"],
    interactionPattern: "slot-input → trigger-cycle → observe-stage-mutation",
    visualMetaphor: "Alchemical distillation pipeline or logic circuit breadboard",
    technology: ["svg", "css", "gsap"],
    complexity: "medium",
    gradeRange: [6, 8],
    estimatedTimeSeconds: [20, 45],
  },
  {
    id: "set-filter-scanner",
    name: "Personnel & Set Exclusion Scanners",
    category: "classification",
    description: "Multi-layered optical scanner filtering population datasets via Boolean conditions (AND, OR, NOT).",
    cognitiveSkills: ["set-theory", "venn-intersection", "exclusion-filtering"],
    interactionPattern: "toggle-filters → scan-sweep → select-intersection-region",
    visualMetaphor: "Personnel record database scanner or sonar biosensor",
    technology: ["svg", "canvas"],
    complexity: "medium",
    gradeRange: [6, 8],
    estimatedTimeSeconds: [15, 40],
  },
  {
    id: "reconstructed-navigation-map",
    name: "Reconstructed Vector Navigation",
    category: "navigation",
    description: "Step-by-step vector trajectory construction tracking cumulative displacement and relative compass bearings.",
    cognitiveSkills: ["direction-sense", "vector-displacement", "compass-bearings"],
    interactionPattern: "input-segments → step-traverse → read-relative-bearing",
    visualMetaphor: "Expeditionary cartography map or lunar rover trajectory plot",
    technology: ["svg", "canvas", "framer-motion"],
    complexity: "medium",
    gradeRange: [6, 8],
    estimatedTimeSeconds: [20, 45],
  },
  {
    id: "structural-crane-construction",
    name: "Structural Assembly & Place-Value Cranes",
    category: "construction",
    description: "Heavy-duty structural placement requiring components to be locked into strict hierarchical or positional order.",
    cognitiveSkills: ["place-value", "hierarchical-ordering", "magnitude-sense"],
    interactionPattern: "crane-pickup → tier-docking → sequence-lock",
    visualMetaphor: "Orbital space station docking tower or skyscraper tier crane",
    technology: ["svg", "css"],
    complexity: "medium",
    gradeRange: [5, 8],
    estimatedTimeSeconds: [15, 35],
  },
  {
    id: "optical-fluid-reflection",
    name: "Dynamic Optical Reflection Pools",
    category: "spatial",
    description: "Liquid or mirror boundary dynamically generating vertical/horizontal inverted reflections with adjustable waterlines.",
    cognitiveSkills: ["water-images", "mirror-inversion", "optical-symmetry"],
    interactionPattern: "drag-waterline → view-wave-inversion → match-reflection",
    visualMetaphor: "Mercury reflection basin or laser optics mirror array",
    technology: ["svg", "css"],
    complexity: "low",
    gradeRange: [5, 8],
    estimatedTimeSeconds: [15, 30],
  },
  {
    id: "crease-folding-studio",
    name: "Crease & Transparency Folding Studios",
    category: "spatial",
    description: "Interactive sheet boundary folding along custom crease lines with live ghost overlay and alpha-composite punch holes.",
    cognitiveSkills: ["paper-folding", "transparency-overlap", "bilateral-symmetry"],
    interactionPattern: "grab-fold-edge → sweep-crease → observe-ghost-composite",
    visualMetaphor: "Origami engineering draft table or holographic laser folder",
    technology: ["svg", "canvas"],
    complexity: "medium",
    gradeRange: [6, 8],
    estimatedTimeSeconds: [20, 40],
  },
  {
    id: "investigation-pinboard",
    name: "Investigative Evidence Pinboards",
    category: "puzzle",
    description: "Node-edge relational network where kinship, connections, and clues are strung together to deduce unknown nodes.",
    cognitiveSkills: ["blood-relations", "graph-deduction", "transitive-logic"],
    interactionPattern: "link-nodes → apply-relation-string → deduce-target-link",
    visualMetaphor: "Forensic detective corkboard with red connective string",
    technology: ["svg", "canvas"],
    complexity: "high",
    gradeRange: [6, 8],
    estimatedTimeSeconds: [25, 55],
  },
  {
    id: "geometric-condition-lens",
    name: "Precision Geometry Condition Scanners",
    category: "spatial",
    description: "Virtual optical loupe and coordinate reticle scanning composite geometric figures to verify dot placement constraints.",
    cognitiveSkills: ["dot-situation", "embedded-figures", "geometric-containment"],
    interactionPattern: "position-lens → scan-overlap → verify-containment-zones",
    visualMetaphor: "Microscopic optical comparator or laser inspection reticle",
    technology: ["svg", "canvas"],
    complexity: "medium",
    gradeRange: [6, 8],
    estimatedTimeSeconds: [20, 45],
  },
  {
    id: "matrix-schedule-planner",
    name: "Matrix Time Schedulers & Calendars",
    category: "everyday",
    description: "Temporal grid engine applying modular arithmetic and conditional rule masks to compute net active time units.",
    cognitiveSkills: ["calendar-math", "modular-arithmetic", "scheduling-logic"],
    interactionPattern: "toggle-rule-filters → auto-highlight-active-days → tally-count",
    visualMetaphor: "Spaceport launch window calendar or dispatch shift matrix",
    technology: ["svg", "css"],
    complexity: "low",
    gradeRange: [5, 8],
    estimatedTimeSeconds: [15, 35],
  },
  {
    id: "mosaic-restoration-table",
    name: "Mosaic & Geometric Tile Restoration",
    category: "puzzle",
    description: "Damaged ornamental tessellation requiring rotation and snap-fitting of missing geometric fragments.",
    cognitiveSkills: ["pattern-completion", "tessellation", "rotational-fit"],
    interactionPattern: "select-tile → rotate-orientation → snap-into-void",
    visualMetaphor: "Archaeological mosaic restoration stage or stained-glass table",
    technology: ["svg", "canvas"],
    complexity: "medium",
    gradeRange: [5, 8],
    estimatedTimeSeconds: [15, 35],
  },
  {
    id: "fractional-area-painter",
    name: "Fractional & Grid Area Painters",
    category: "data",
    description: "Interactive surface coating roller displaying live fractional, percentage, and ratio meters during fill operations.",
    cognitiveSkills: ["fractional-area", "part-to-whole", "grid-shading"],
    interactionPattern: "drag-paint-roller → fill-cells → monitor-fraction-meter",
    visualMetaphor: "Photovoltaic solar array energizer or agricultural grid sprayer",
    technology: ["svg", "canvas"],
    complexity: "low",
    gradeRange: [5, 8],
    estimatedTimeSeconds: [15, 30],
  },
  {
    id: "mathematical-tree-cascade",
    name: "Mathematical Trees & Dependency Cascades",
    category: "puzzle",
    description: "Multi-tier branching hierarchy where leaf evaluations cascade upwards through operations to feed root objectives.",
    cognitiveSkills: ["factor-trees", "dependency-propagation", "prime-decomposition"],
    interactionPattern: "activate-leaves → propagate-values → solve-missing-junction",
    visualMetaphor: "Hydroelectric dam valve cascade or cybernetic root mainframe",
    technology: ["svg", "gsap"],
    complexity: "medium",
    gradeRange: [6, 8],
    estimatedTimeSeconds: [20, 45],
  },
  {
    id: "ballistic-kinematic-railway",
    name: "Ballistic Kinematics & Synchronizers",
    category: "physics",
    description: "Multiple discrete frequency walkers or trajectory rails executing concurrently to reveal mutual periodic convergence.",
    cognitiveSkills: ["lcm-hcf", "periodic-motion", "synchronization"],
    interactionPattern: "set-step-frequencies → launch-parallel → observe-coincidence",
    visualMetaphor: "Synchronized step frequency corridor or celestial orbit transit",
    technology: ["canvas", "svg"],
    complexity: "medium",
    gradeRange: [6, 8],
    estimatedTimeSeconds: [20, 45],
  },
  {
    id: "equilibrium-torque-balance",
    name: "Equilibrium & Dynamic Torque Balances",
    category: "physics",
    description: "Calibrated lever beam scale calculating live moment arm torque and integer weight differentials.",
    cognitiveSkills: ["linear-equations", "signed-integers", "moment-equilibrium"],
    interactionPattern: "load-weights-to-pan → balance-beam-tilts → achieve-level",
    visualMetaphor: "Ancient brass jeweler's balance or airship center-of-mass trim",
    technology: ["svg", "canvas", "matter-js"],
    complexity: "medium",
    gradeRange: [5, 8],
    estimatedTimeSeconds: [15, 40],
  },
  {
    id: "symmetry-axis-sweeper",
    name: "Symmetry Axis Sweepers",
    category: "spatial",
    description: "360-degree rotational optical laser line identifying and snapping to all valid axes of reflectional symmetry.",
    cognitiveSkills: ["lines-of-symmetry", "rotational-invariance", "geometric-axes"],
    interactionPattern: "rotate-laser-axis → match-halves → lock-symmetry-line",
    visualMetaphor: "Gemological laser scanner or optical wafer alignment chamber",
    technology: ["svg", "canvas"],
    complexity: "low",
    gradeRange: [5, 8],
    estimatedTimeSeconds: [15, 35],
  },
  {
    id: "data-turnstile-workshop",
    name: "Data Flow Turnstiles & Statistical Workshops",
    category: "data",
    description: "Dynamic particle emitter translating raw tally frequencies into responsive sector pie and bar flow models.",
    cognitiveSkills: ["tally-interpretation", "frequency-distributions", "proportions"],
    interactionPattern: "stream-tally-groups → dynamic-sector-aggregation → compare-sums",
    visualMetaphor: "Transit station automated passenger turnstile or wildlife telemetry gate",
    technology: ["svg", "canvas"],
    complexity: "medium",
    gradeRange: [5, 8],
    estimatedTimeSeconds: [20, 40],
  },
  {
    id: "spatial-decomposition-planner",
    name: "Spatial Decomposition & Wire Tensioners",
    category: "measurement",
    description: "Dissection tool breaking complex irregular stepped/spiral polygons into computable rectangles, or bending perimeter wire.",
    cognitiveSkills: ["area-decomposition", "perimeter-constraints", "compound-geometry"],
    interactionPattern: "draw-dissection-rays → calculate-subregions → sum-total",
    visualMetaphor: "Architectural CNC laser cutter or wire bending jig",
    technology: ["svg", "canvas"],
    complexity: "high",
    gradeRange: [6, 8],
    estimatedTimeSeconds: [25, 50],
  },
  {
    id: "mechanical-clockwork-probe",
    name: "Mechanical Clockwork & Angle Sector Probes",
    category: "measurement",
    description: "Geared dual-hand analog clock dial with dynamic angular arc sweep measuring exact acute, obtuse, and reflex degrees.",
    cognitiveSkills: ["clock-angles", "angular-measure", "elapsed-time"],
    interactionPattern: "rotate-clock-hands → sweep-angle-arc → verify-angle-classification",
    visualMetaphor: "Precision horological chronometer or nautical astrolabe",
    technology: ["svg", "canvas"],
    complexity: "low",
    gradeRange: [5, 8],
    estimatedTimeSeconds: [15, 35],
  },
  {
    id: "hydrodynamic-vessel-lab",
    name: "Hydrodynamic & Volumetric Vessels",
    category: "physics",
    description: "Interconnected transparent fluid reservoirs with calibrated height gauges comparing fraction volumes in real time.",
    cognitiveSkills: ["fraction-comparison", "liquid-volume", "capacitive-ratios"],
    interactionPattern: "adjust-flow-valves → equalize-fluid-heights → evaluate-volume",
    visualMetaphor: "Chemical titration manifold or submarine ballast tank controller",
    technology: ["svg", "css"],
    complexity: "medium",
    gradeRange: [5, 8],
    estimatedTimeSeconds: [15, 40],
  },
  {
    id: "calculation-factory-pipeline",
    name: "Industrial Calculation & Operator Pipelines",
    category: "transformation",
    description: "Conveyor belt where operand containers pass through redefined operational stations under altered BODMAS rules.",
    cognitiveSkills: ["operator-substitution", "bodmas-precedence", "symbolic-mapping"],
    interactionPattern: "insert-operator-chips → run-pipeline → watch-operand-transformation",
    visualMetaphor: "Pneumatic computation factory or cybernetic decryption pipeline",
    technology: ["svg", "css", "gsap"],
    complexity: "medium",
    gradeRange: [6, 8],
    estimatedTimeSeconds: [20, 45],
  },
  {
    id: "archaeological-numeral-decoder",
    name: "Archaeological Numeral Decoders",
    category: "puzzle",
    description: "Ancient stone tablet laser scanner translating archaic glyphs and Roman expressions into Arabic equivalents.",
    cognitiveSkills: ["roman-numerals", "base-systems", "ancient-arithmetic"],
    interactionPattern: "scan-inscriptions → translate-subtractive-rules → scale-placement",
    visualMetaphor: "Museum artifact holographic scanner or temple inscription chamber",
    technology: ["svg", "motion"],
    complexity: "medium",
    gradeRange: [5, 8],
    estimatedTimeSeconds: [20, 40],
  },
  {
    id: "metrology-conversion-dynamo",
    name: "Metrology & Unit Conversion Dynamos",
    category: "measurement",
    description: "Multi-dial metric/customary gear train translating prefixes ($kilo \\leftrightarrow hecto \\leftrightarrow deci \\leftrightarrow milli$) in real time.",
    cognitiveSkills: ["unit-conversion", "dimensional-analysis", "scale-factors"],
    interactionPattern: "shift-prefix-gearbox → observe-dynamometer-translation → match-units",
    visualMetaphor: "Laboratory calibration dynamometer or pressure gauge manifold",
    technology: ["svg", "css"],
    complexity: "low",
    gradeRange: [5, 8],
    estimatedTimeSeconds: [15, 35],
  },
  {
    id: "sequential-commerce-journey",
    name: "Sequential Commerce & Expenditure Flows",
    category: "everyday",
    description: "Step-by-step passage through sequential expenditure checkpoints with a live wallet ledger tracking fractional decay.",
    cognitiveSkills: ["fraction-of-remainder", "reverse-unitary-method", "financial-arithmetic"],
    interactionPattern: "traverse-storefronts → deduct-fractional-shares → deduce-initial-wallet",
    visualMetaphor: "Mountain expedition supply outpost trail or merchant bazaar",
    technology: ["svg", "css"],
    complexity: "medium",
    gradeRange: [6, 8],
    estimatedTimeSeconds: [20, 45],
  },
  {
    id: "kinematic-track-race",
    name: "Kinematic Track Races & Differential Odometers",
    category: "physics",
    description: "Simultaneous runners traversing distinct geometric perimeters with live telemetry odometers computing cumulative delta.",
    cognitiveSkills: ["perimeter-multiplication", "relative-distance", "rate-differentials"],
    interactionPattern: "start-dual-racers → monitor-lap-telemetry → read-final-gap",
    visualMetaphor: "Velodrome cycling trial or drone circuit telemetry console",
    technology: ["svg", "canvas", "framer-motion"],
    complexity: "medium",
    gradeRange: [6, 8],
    estimatedTimeSeconds: [20, 45],
  },
  {
    id: "microclimate-differential-station",
    name: "Microclimate & Gradient Weather Stations",
    category: "everyday",
    description: "Comparative dual-environment probe stations with vertical mercury column thermometers exploring signed temperature spans.",
    cognitiveSkills: ["integer-subtraction", "temperature-deltas", "zero-origin-scaling"],
    interactionPattern: "adjust-elevation-probe → measure-thermal-span → calculate-differential",
    visualMetaphor: "Arctic vs Desert atmospheric telemetry station",
    technology: ["svg", "css"],
    complexity: "low",
    gradeRange: [5, 8],
    estimatedTimeSeconds: [15, 30],
  },
  {
    id: "industrial-packing-tessellation",
    name: "Industrial Packing & Tessellation Cutters",
    category: "measurement",
    description: "Automated sheet cutter computing integer 2D bounding grid yield and container packing without fractional waste.",
    cognitiveSkills: ["integer-division", "2d-tessellation-packing", "remainder-optimization"],
    interactionPattern: "configure-cutting-matrix → preview-sheet-yield → count-complete-units",
    visualMetaphor: "High-speed envelope manufacturing plant or CNC sheet laser cutter",
    technology: ["canvas", "svg"],
    complexity: "medium",
    gradeRange: [6, 8],
    estimatedTimeSeconds: [20, 45],
  },
  {
    id: "subzero-integer-shaft",
    name: "Sub-Zero Integer Shafts & Elevation Trails",
    category: "physics",
    description: "Vertical elevator shaft penetrating above and below zero sea level exploring signed integers, successors, and predecessors.",
    cognitiveSkills: ["signed-integers", "successor-predecessor", "absolute-value"],
    interactionPattern: "operate-shaft-winch → cross-zero-origin → record-floor-delta",
    visualMetaphor: "Deep-sea bathysphere research elevator or mining hoist",
    technology: ["svg", "css"],
    complexity: "low",
    gradeRange: [5, 8],
    estimatedTimeSeconds: [15, 35],
  },
  {
    id: "achiever-multistage-vault",
    name: "Achiever Multi-Stage Challenge Vaults",
    category: "achiever",
    description: "High-order multi-room verification laboratory requiring two-stage hypothesis testing, evidence locking, and compound logic.",
    cognitiveSkills: ["statement-verification", "compound-reasoning", "multi-step-deduction"],
    interactionPattern: "test-statement-1 → record-evidence → test-statement-2 → lock-master-key",
    visualMetaphor: "Quantum containment facility multi-key vault or cyber-forensic terminal",
    technology: ["svg", "canvas", "framer-motion"],
    complexity: "high",
    gradeRange: [6, 8],
    estimatedTimeSeconds: [30, 60],
  },
];

export function getParadigmById(id: string): Archetype | undefined {
  return THE_29_PARADIGMS.find(p => p.id === id);
}

export function getAllParadigms(): Archetype[] {
  return [...THE_29_PARADIGMS];
}
