import { Cloud, Lamp, Lightbulb, Luggage, Mountain, Phone, Search, ShoppingBag, Store, BookOpen, Landmark } from "lucide-react";
import type { StorySpec } from "./story";
import {
  CatchUpWorld, GatheringCloudsWorld, ImmigrantsWorld, InventWorld, JumpInWorld, MountainRoadWorld, PhoneCallWorld,
  PowerCutWorld, SaleWorld, ShopClosingWorld, TraditionsWorld, WhoseHouseWorld,
} from "./worldsB";

/* Q13–Q24 */
export const SPECS_B: Record<number, StorySpec> = {
  13: {
    title: "The Missed Call",
    mission: "He spots the lady he met yesterday — the one he has been trying to phone. Finish his sentence.",
    icon: Phone,
    World: PhoneCallWorld,
    bubbleAt: [-0.8, 2.1, 0.6],
    mech: { kind: "fill", template: "She's the lady I met yesterday and ___ number I was trying to call just now.", speaker: "On the phone" },
    hints: ["The gap links the lady to something that belongs to her.", "Which word shows that the number is hers?"],
  },
  14: {
    title: "Sale Day",
    mission: "The sale is on — and the purse is empty again. Complete the shopper's complaint.",
    icon: ShoppingBag,
    World: SaleWorld,
    bubbleAt: [0.3, 2.1, 0.5],
    mech: { kind: "fill", template: "Every time I go to the sales, I forget to take ___ money.", speaker: "The shopper" },
    hints: ["She means her own particular money for the trip, not money in general.", "Which article points to a specific thing both speakers know about?"],
  },
  15: {
    title: "The Gathering Storm",
    mission: "Watch the wind push the clouds together. Describe what the clouds started doing.",
    icon: Cloud,
    World: GatheringCloudsWorld,
    bubbleAt: [0.2, 2.1, 0.6],
    mech: { kind: "fill", template: "As the wind blew, the clouds started ___, making the sky turn grey." },
    hints: ["After “started” we use either “to + verb” or a verb ending in “-ing”.", "Only one tile fits straight after “started” here."],
  },
  16: {
    title: "The Power Cut",
    mission: "She was in the middle of handing him a lamp when the lights went out. Finish the story.",
    icon: Lamp,
    World: PowerCutWorld,
    bubbleAt: [0.75, 2.1, -0.2],
    mech: { kind: "fill", template: "Before the electricity went out, she ___ me a lamp with my homework.", speaker: "The boy" },
    hints: ["The action was in progress in the past when something else happened.", "Which tense describes an action that was going on at a past moment?"],
  },
  17: {
    title: "Jump Right In",
    mission: "She loves this job so much she throws herself into it. Complete her saying.",
    icon: Lightbulb,
    World: JumpInWorld,
    bubbleAt: [0, 2.1, 0.4],
    mech: { kind: "fill", template: "I always jump ___ with both feet on tasks that I enjoy.", speaker: "The gardener" },
    hints: ["This is an idiom: to start something eagerly, without holding back.", "Imagine jumping into a pool with both feet — which little word fits?"],
  },
  18: {
    title: "Catch-Up Weekend",
    mission: "A tall pile of missed work and a whole weekend. Complete her plan — and watch the pile shrink.",
    icon: BookOpen,
    World: CatchUpWorld,
    bubbleAt: [-0.2, 2.1, 0.1],
    mech: { kind: "fill", template: "I have to study all weekend, so I can catch up ___ the work I missed last week.", speaker: "The student" },
    hints: ["“Catch up” is followed by the same preposition every time you mean ‘do the work you missed’.", "Try: “catch up ___ your reading”."],
  },
  19: {
    title: "Old Traditions",
    mission: "The town takes down the board of old rules. Finish what the townsperson says.",
    icon: Landmark,
    World: TraditionsWorld,
    bubbleAt: [0.5, 2.1, 0.3],
    mech: { kind: "fill", template: "I agree that the ___ of some old traditions makes sense today.", speaker: "A townsperson" },
    hints: ["The gap is a noun for what is happening to the old rules.", "Which word means “ending something officially”?"],
  },
  20: {
    title: "The Inventor's Idea",
    mission: "Gears are turning and an idea is forming. Finish the inventor's thought.",
    icon: Lightbulb,
    World: InventWorld,
    bubbleAt: [0.2, 2.1, 0.1],
    mech: { kind: "fill", template: "It is really difficult to ___ and create something new.", speaker: "The inventor" },
    hints: ["After “to” we need a verb, and it pairs with “create”.", "Which verb means “bring in new ideas”?"],
  },
  21: {
    title: "The Pothole Road",
    mission: "The car bumps up a road full of holes. Describe the road's reputation.",
    icon: Mountain,
    World: MountainRoadWorld,
    bubbleAt: [-0.6, 2.1, 1.0],
    mech: { kind: "fill", template: "The road up that mountain is ___ because of the dangerous holes in it.", speaker: "The walker" },
    hints: ["The road is famous for something bad.", "Which word means “well known for being bad or dangerous”?"],
  },
  22: {
    title: "A New Home",
    mission: "Follow their journey on the map. Finish what she tells her new classmates.",
    icon: Luggage,
    World: ImmigrantsWorld,
    bubbleAt: [-0.9, 2.1, 0.3],
    mech: { kind: "fill", template: "I am not from here originally; my family are ___.", speaker: "The newcomer" },
    hints: ["The first half explains the second: they came from another country.", "Which word names people who come to live in a new country?"],
  },
  23: {
    title: "Closing Time",
    mission: "Read the shop's sign-off sentence carefully. Plant the flag on the part that contains the mistake.",
    icon: Store,
    World: ShopClosingWorld,
    bubbleAt: [-1.2, 2.1, 0.8],
    mech: { kind: "error", before: "Drag the flag onto the part of the sentence that has the error." },
    hints: ["Check each part for grammar, not meaning.", "Look closely at how ownership is shown."],
  },
  24: {
    title: "Whose House?",
    mission: "The detective's note has a mistake in it. Plant the flag on the faulty part.",
    icon: Search,
    World: WhoseHouseWorld,
    bubbleAt: [-0.4, 2.1, 0.3],
    mech: { kind: "error", before: "Drag the flag onto the part of the sentence that has the error." },
    hints: ["One part says the same thing twice.", "Read each part and ask: is any word unnecessary?"],
  },
};

