import { Bath, Bug, Bus, Flower2, Footprints, Hotel, Pizza, Presentation, Snowflake, ThermometerSun, Trophy, UtensilsCrossed } from "lucide-react";
import type { StorySpec } from "./story";
import {
  BusFareWorld, HandballWorld, HotelWorld, HotWaterWorld, InsectWorld, ItalianFoodWorld, LongWalkWorld, PizzaStreetWorld,
  ReportWorld, SnowWorld, SwimWishWorld, VaseWorld,
} from "./worldsA";

/* Q1–Q12: finish the sentence the characters are saying. */
export const SPECS_A: Record<number, StorySpec> = {
  1: {
    title: "Pizza Street",
    mission: "Every pizzeria on the street is shut. Finish what the friends say about it.",
    icon: Pizza,
    World: PizzaStreetWorld,
    bubbleAt: [0, 2.1, 0.5],
    mech: { kind: "fill", template: "It's a ___ that there aren't any good pizzerias in this town.", speaker: "Friends on Pizza Street" },
    hints: ["After “a”, the gap needs a noun — a thing, not an action or a describing word.", "Which tile names a feeling of disappointment?"],
  },
  2: {
    title: "Hotel Checkout",
    mission: "The guest's wallet is empty, so they must leave the hotel. Complete the reason they give.",
    icon: Hotel,
    World: HotelWorld,
    bubbleAt: [0.6, 2.1, 0.2],
    mech: { kind: "fill", template: "I couldn't stay any longer due ___ having enough money to pay for the hotel.", speaker: "The guest" },
    hints: ["“Due” is always followed by the same little word before the reason.", "The guest did NOT have enough money — where does the “not” go?"],
  },
  3: {
    title: "Handball Rally",
    mission: "Frank and Jane rally the ball — but which of them is the star? Finish the spectator's thought.",
    icon: Trophy,
    World: HandballWorld,
    bubbleAt: [2.3, 2.0, 1.3],
    mech: { kind: "fill", template: "Either Frank or Jane ___ handball really well, but I can never remember who though.", speaker: "The spectator" },
    hints: ["With “either … or”, the verb agrees with the person nearest to it.", "“Jane” is one person, and this is a present-time fact."],
  },
  4: {
    title: "First Snow",
    mission: "A visitor from a warm place meets snow. Finish what they say, still shivering.",
    icon: Snowflake,
    World: SnowWorld,
    bubbleAt: [0.5, 2.1, 0.3],
    mech: { kind: "fill", template: "Being from a warm southern climate, I ___ snow before, so it is quite a shock.", speaker: "The visitor" },
    hints: ["“before” links the past to right now — which tense does that?", "The visitor has never had this experience until now."],
  },
  5: {
    title: "The Knocked-Over Vase",
    mission: "The flowers have been knocked over. Describe HOW he puts them back — and watch him do it.",
    icon: Flower2,
    World: VaseWorld,
    bubbleAt: [0.9, 2.0, 0.5],
    mech: { kind: "fill", template: "He ___ put the flowers back in the vase after knocking them over." },
    hints: ["The gap describes the way he put them back.", "Words that describe how an action is done often end in “-ly”."],
  },
  6: {
    title: "Under the Magnifying Glass",
    mission: "The ladybird is almost invisible. Describe its size so the scientist can explain.",
    icon: Bug,
    World: InsectWorld,
    bubbleAt: [1.1, 2.1, 0.5],
    mech: { kind: "fill", template: "The ___ size of the insect makes it very difficult to see without a magnifying glass.", speaker: "The scientist" },
    hints: ["The gap describes the size of something.", "Which word means “extremely small”? (A nanometre is a unit, not a description.)"],
  },
  7: {
    title: "The Unconvincing Report",
    mission: "Nobody in the meeting is convinced. Finish the presenter's worry.",
    icon: Presentation,
    World: ReportWorld,
    bubbleAt: [-0.2, 2.1, 0.5],
    mech: { kind: "fill", template: "It will be very difficult to persuade them to do anything ___ the information in this report.", speaker: "The presenter" },
    hints: ["The information is the tool they would act with.", "Try each little word: which one means “using”?"],
  },
  8: {
    title: "The Long Walk",
    mission: "The hiker is worn out. Finish their thought — then watch them reach the finish.",
    icon: Footprints,
    World: LongWalkWorld,
    bubbleAt: [0, 2.1, 1.0],
    mech: { kind: "fill", template: "I will be glad ___ this walk is finally over.", speaker: "The hiker" },
    hints: ["The gap tells us at what moment the hiker will be glad.", "Which word introduces a time?"],
  },
  9: {
    title: "Italian Feast",
    mission: "Look at the plates Edward has cleared. Finish the waiter's remark.",
    icon: UtensilsCrossed,
    World: ItalianFoodWorld,
    bubbleAt: [1.3, 2.1, -0.9],
    mech: { kind: "fill", template: "Edward ___ a lot of Italian food, hasn't he?", speaker: "The waiter" },
    hints: ["Look at the question tag at the end: “hasn't he?”", "The tag matches the helping verb used in the gap."],
  },
  10: {
    title: "Jenny's Wish",
    mission: "Jenny is bouncing by the pool. Punctuate what she says so the sentence is written properly.",
    icon: Bath,
    World: SwimWishWorld,
    bubbleAt: [-0.3, 2.1, 0.4],
    mech: { kind: "fill", template: "“I want to go swimming___ said Jenny." },
    hints: ["The speech is not the end of the sentence — “said Jenny” follows it.", "Which mark goes inside the closing quotation mark when the sentence carries on?"],
  },
  11: {
    title: "Steaming Water",
    mission: "The water is steaming and the thermometer is in the red. Finish the warning.",
    icon: ThermometerSun,
    World: HotWaterWorld,
    bubbleAt: [-0.9, 2.1, 0.7],
    mech: { kind: "fill", template: "I don't think that the water is ___ hot for you to swim in today.", speaker: "The lifeguard" },
    hints: ["“___ hot for you to swim” — the heat goes beyond what is OK.", "Which word means “more than is right”?"],
  },
  12: {
    title: "The Bus Fare",
    mission: "She is counting her coins at the bus stop. Finish her plan.",
    icon: Bus,
    World: BusFareWorld,
    bubbleAt: [0, 2.1, -0.2],
    mech: { kind: "fill", template: "If the bus fare costs more than I thought, I ___ have to walk to the shops.", speaker: "At the bus stop" },
    hints: ["“If … costs” is a real possibility in the present.", "Which helping verb talks about what WILL happen then?"],
  },
};
